name: python-CI
on:
  workflow_dispatch:
    inputs:
      name:
        description: "please enter your name"
        type: string
      age:
        description: "please enter your age"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set-up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Calculate_age/requirements.txt

      - name: run python tests
        run:
          pytest Calculate_age/ || true

      - name: Run the script
        run: |
          printf "${{ github.event.inputs.name }}\n${{ github.event.inputs.age }}\n" | python Calculate_age/calculate.py

      - name: printing
        id: info-output
        run: |
          echo "actor: ${{github.actor}}" >> $GITHUB_OUTPUT
          echo "repo url: https://github.com/${{github.url}}" >> $GITHUB_OUTPUT

      - name: printing the stored values
        run: |
          echo "Actor from info-output: ${{steps.info-output.outputs.actor"
          echo "Repo url from info-output: ${{steps.info-output.outputs.repo url"
  
